/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;
import koneksi.koneksi;
/**
 *
 * @author Hadi Firmansyah
 */
public class menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form option_menu
     */
    public menu_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_riwayat = new javax.swing.JButton();
        btn_datapetugas = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_databarang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 119, 141));

        btn_riwayat.setBackground(new java.awt.Color(204, 204, 255));
        btn_riwayat.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/riwayat.png"))); // NOI18N
        btn_riwayat.setText("Riwayat");
        btn_riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_riwayatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        btn_datapetugas.setBackground(new java.awt.Color(204, 204, 255));
        btn_datapetugas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_datapetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/datapetug.png"))); // NOI18N
        btn_datapetugas.setText("Data Petugas");
        btn_datapetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datapetugasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_datapetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        btn_logout.setBackground(new java.awt.Color(204, 204, 255));
        btn_logout.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        btn_databarang.setBackground(new java.awt.Color(204, 204, 255));
        btn_databarang.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_databarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/databarang.png"))); // NOI18N
        btn_databarang.setText("Data Barang");
        btn_databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databarangActionPerformed(evt);
            }
        });
        jPanel1.add(btn_databarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/MAN2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 57));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/more-leaves.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 220, 300));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/more-leaves.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_riwayatActionPerformed
        new report.riwayat().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_riwayatActionPerformed

    private void btn_datapetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datapetugasActionPerformed
        new akun_petugas().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_datapetugasActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        new login.menu_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databarangActionPerformed
        new formCRUDBarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_databarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_databarang;
    private javax.swing.JButton btn_datapetugas;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_riwayat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
